### ISSUE TITLE
[Bug] P tags end up within jsx blocks

### ISSUE THREAD

**Issue by johno** [fazouane-marouane/remark-jsx#20]
The following:

```jsx
<Button>
  Bar
</Button>
```

Results in:

```html
<button>
  <p>Bar</p>
</button>
```

Not sure what the approach should be here since we can't exactly determine whether a component type is phrasing content or not, and interleaving paragraph content is seemingly nearly impossible to determine. Perhaps we can make interleaved jsx + md an option or a static attribute on the component itself?

```jsx
const Button = props => <button {..props} />
Button.interleave = false
// ...
```

We've been toying with an [`.mdx` specification](https://github.com/c8r/markdown/blob/master/MDX_SPECIFICATION.md), and I'm still going back and forth on whether md + jsx should be interleaved or not.

**Comment by fazouane-marouane** [comment]
This is due to the fact that Button in the example has been used as a "block" element, in remarkjs terminology. So it expects block elements as children. That's where the P element comes from 🙁 

Maybe the .mdx specification is the way to go in this case, maybe individual option per component would do or maybe we can drop the P element if it's the only child of a "custom element".

I don't know what's the most intuitive option here.

**Comment by wooorm** [comment]
Closing due to deprecation. See https://github.com/remarkjs/remark-jsx/issues/22#issuecomment-451562940 for more info.
