### ISSUE TITLE
Future

### ISSUE THREAD

**Issue by wooorm** [fazouane-marouane/remark-jsx#22]
So, what’s the future with this?

* Should we link to MDX?
* Should we deprecate this?
* Are there differences and should this be fleshed out some more?

/CC @fazouane-marouane @johno

**Comment by fazouane-marouane** [comment]
Hi @wooorm 

Personally, since all attention and efforts have been directed to mdx, I don't see any reason to further this project. Also, the community seems quite satisfied with the solution brought by mdx which is a good indicator to not start a competing implementation (although it might be technically possible).

So unless there's any objection, I'm okay with deprecating this project.

**Comment by wooorm** [comment]
Alright, MDX is growing. I’m going to deprecate this!

Thanks for all the amazing work on this @fazouane-marouane!

For people coming here, please use [MDX](https://github.com/mdx-js/mdx) instead!
